### PR TITLE
Fix: create records using `for_each` instead of `count`

### PR DESCRIPTION
**Pull request by 1david5**
## what
* Modify `default` and `ipv6` `aws_route53_record` resources to use `for_each` instead of `count`.

## why
* Prevent destroying and recreating DNS records when removing elements from `aliases` list.

### CODE REVIEW

**Review by korenyoni — APPROVED** [review]
Looks good to me.

**Comment by korenyoni** [comment]
Hope you don't mind I take this opportunity to update the contributors list in `README.md` (via `README.yaml`) 😄

**Review by korenyoni — APPROVED** [review]
LGTM

**Comment by korenyoni** [comment]
Note that this is a minor release because it will cause destruction and recreation of resources due to the address change.

**Comment by 1david5** [comment]
Perfect. thank you @korenyoni 👍

**Pull request merged**
